### ISSUE TITLE
Don't Start Server

### ISSUE THREAD

**Issue by yearnwang** [mr-m0nst3r/Burpy#2]
System OS: win10
Burpy version: 1.2.1

I install Burpy ok, Show question When I Click Start Sever Button. 
Please tell me , How I solve the question?
thanks,

<img width="498" alt="微信截图_20200514112208" src="https://user-images.githubusercontent.com/5487767/81889197-8c248e00-95d5-11ea-927d-1efc97d2c403.png">

**Comment by yearnwang** [comment]
but I start server ok When I use brida

**Comment by mr-m0nst3r** [comment]
@yearnwang this can result from many reasons, but first step is to make sure the python script you want to load don't have errors.

You can check this by running the script directly from terminal or console, like below:

![image](https://user-images.githubusercontent.com/38524240/81889700-c93d5000-95d6-11ea-882b-4b8fa9c06cc3.png)


Usually because of syntax errors or dependency errors.

Let me know how it works for you.

**Comment by mr-m0nst3r** [comment]
@yearnwang if you also use Brida, which I love the most, double check the pyro port, specify a different port with Brida.

**Comment by yearnwang** [comment]
script issue
Beasuse, I uses https://github.com/mr-m0nst3r/Burpy/blob/master/examples/aes_endec.py，but my system have not AES modules.

Now, Startserver successful,
thanks
